### ISSUE TITLE
'admin' user should be added to the 'www-data' group for compatibility

### ISSUE THREAD

**Issue by pcammish** [BytemarkHosting/symbiosis#115]
In quite a few cases where web apps update themselves, such as WordPress, the updaters check that specific files and directories are owned by the user Apache is running as, and fail if they don't match.

By adding the `admin` user to the `www-data` group, and setting ownership to be www-data:www-data, both the web app and Symbiosis FTP users can update files and directories as needed without stepping on each others toes too much.

Note that this will often require the group to be set to www-data also (and sometimes rw permissions set for the group), but this prevents web app installs from arguing with the admin permissions, and allows the admin user (ie: the user used with FTP) to overwrite files as needed.

**Comment by andrewladlow** [comment]
Fixed by 7f7390819b0ed157098a645145cc979fb2b7f1e8
