### ISSUE TITLE
Apache PHP7 module isn't enabled automatically following dist-upgrade from Symbiosis Jessie

### ISSUE THREAD

**Issue by andrewladlow** [BytemarkHosting/symbiosis#116]
During the dist-upgrade from Symbiosis Jessie to Stretch, Apache will not enable the PHP7 module as it conflicts with PHP5 (which should already be enabled). The PHP5 module should therefore be explicitly disabled in favour of PHP7.

**Comment by banburybill** [comment]
I see Bytemark have now done this. This action, though, broke the website on one of the hosts I manage.

Yes, the website uses an old PHP framework which doesn't work on PHP7. We're slowly working towards replacing it. But it's not there yet, and I think that, convenient as it may be for Symbiosis, upgrading the system PHP version in this manner isn't quite the done thing.

**Comment by andrewladlow** [comment]
We've reverted this so that it'll behave as a standard Debian Jessie -> Stretch dist-upgrade would - informing the user that PHP7 modules won't be enabled, but not forcing them instead of PHP5. 

The idea was to streamline the dist-upgrade process for users who were perhaps not all that confident with the Linux command line, but having them manually disable/enable Apache mods is definitely preferable to breaking sites that aren't quite ready for PHP7. :slightly_smiling_face:
