### ISSUE TITLE
Hook support for Symbiosis-SSL

### ISSUE THREAD

**Issue by jiphex** [BytemarkHosting/symbiosis#12]
It's common that the Lets Encrypt SSL certificates procured by Symbiosis for HTTPS might be used by other services, however there's currently no way for other applications configured by the user (e.g HAProxy, mail daemons, secondary servers etc) to know when a certificate has been updated other than by polling.

It would be nice if Symbiosis were to be able to `run-parts` on a specific directory whenever a domain's cert is rolled over so that other daemons could be notified. The environment should include information about the new certificates so that scripts could do whatever processing was necessary to use the new certificate.

**Comment by patch0** [comment]
@jiphex what would you expect to be passed?  Would a list of domains that have had their certificates updated be sufficient?

I'm thinking about an environment variable of space separated domains whose certificates have changed passed into run-parts.

**Comment by patch0** [comment]
The alternative is to call run-parts once for each domain, as it is renewed, using the `--arg` parameter in run-parts to pass the domain name in question.

**Comment by jiphex** [comment]
It'd be nice if the format was the same as the acmetool hooks so you could re-use the same code. With their spec, the first argument is the event type (they use "live-updated" to mean that the "live" symlink/cert has been updated") and then they pass the domains that have changed to STDIN, one per line.

https://github.com/hlandau/acme/blob/master/_doc/SCHEMA.md#hooks is their spec

**Comment by patch0** [comment]
Passing stuff on STDIN means writing our own run-parts replacement.  As it stands, as it means I can't just shell out to run-parts, I don't think.

It could be quite simple, I suppose

```ruby
Dir.glob('/path/to/scripts/*').each do |script| 
  next unless File.executable?(script)
  next unless File.basename(script) =~ /some suitable regex/
  IO.popen([script, 'live-update'], 'r+') do |io|
    io.puts domains_with_updates.join("\n")
    io.close_write                   # Close the pipe now we've written stuff.
    puts io.gets while !io.eof? # if we're expecting to get stuff back
  end
end
```

**Comment by patch0** [comment]
Just need to handle duff exit codes.  I suspect we'd ignore them, or print something out.  This runs under cron, so output would get emailed to root.

**Comment by telyn** [comment]
I don't think we really need a regex for the filenames. We probably want to ensure they're in lexical order by filename.

**Comment by telyn** [comment]
Patrick has pointed out that hidden files probably don't wanna be executed.
