### ISSUE TITLE
Frequently used packages aren't installed by default

### ISSUE THREAD

**Issue by andrewladlow** [BytemarkHosting/symbiosis#120]
There are a number of packages which are typically installed manually on a newly created Symbiosis server as a first priority, since they're used so often. The following packages are sure bets to be installed in most cases:
`curl, iotop, less, lsof, psmisc, rsync, screen, smartmontools, telnet, vim, wget, htop, mtr-tiny, xfsprogs, tree, dnsutils`

It would be useful if we could add these packages as a Symbiosis dependency to ensure they're installed automatically.

**Comment by ianeiloart** [comment]
er, dnsutils ?

**Comment by andrewladlow** [comment]
For dig :)

**Comment by andrewladlow** [comment]
These packages are now pre-installed when imaged with Bytemark.
