### ISSUE TITLE
Deprecated File.exists? call used by symbiosis-httpd-configure in Stretch

### ISSUE THREAD

**Issue by andrewladlow** [BytemarkHosting/symbiosis#121]
Running `symbiosis-httpd-configure -vdf` returns a deprecated `File.exists?` warning, as per:

<pre>
root@blank:~# symbiosis-httpd-configure -vdf
Configuration: blank.default.aladlow.uk0.bigv.io.conf
	Forcing re-creation of configuration due to --force.
/usr/lib/ruby/vendor_ruby/symbiosis/config_file.rb:138: warning: File.exists? is a deprecated name, use File.exist? instead
	Syntax OK
Configuration: zz-mass-hosting.conf
	Forcing re-creation of configuration due to --force.
/usr/lib/ruby/vendor_ruby/symbiosis/config_file.rb:138: warning: File.exists? is a deprecated name, use File.exist? instead
	Syntax OK
Configuration: zz-mass-hosting.ssl.conf
	Forcing re-creation of configuration due to --force.
/usr/lib/ruby/vendor_ruby/symbiosis/config_file.rb:138: warning: File.exists? is a deprecated name, use File.exist? instead
	Syntax OK
</pre>

**Comment by jamielinux** [comment]
Fixed by https://github.com/BytemarkHosting/symbiosis/commit/6fa0cad9002f18eba03beaf2e091dfb54861f22d
