### ISSUE TITLE
On Stretch, httpd.postinst doesn't correctly preserve `no-stats` settings

### ISSUE THREAD

**Issue by jamielinux** [BytemarkHosting/symbiosis#124]
This is what I think should happen:

1. If `no-stats` is present and not set to `false`: remove, as this is the default now.
2. If `no-stats` is present and set to `false`: move to `stats` and truncate, ensuring stats are enabled.
3. If `no-stats` isn't present: create `stats`.
4. Otherwise do nothing.

Patrick advised that we can potentially not do (3) and just put in release notes that the default is now that stats are disabled by default, as we use webalizer which is old and clunky and potentially many customers don't use it.

**Comment by andrewladlow** [comment]
Fixed by 4c9e5a942dde4c421f84fec8a3588c29422ef2db
