### ISSUE TITLE
/etc/ssl/ssl.combined missing on fresh install

### ISSUE THREAD

**Issue by DavidusEdwardus** [BytemarkHosting/symbiosis#125]
/etc/ssl/ssl.combined seems to be missing on a fresh install, though referenced in the Exim config.

This has the effect of the following on SMTP STARTTLS

454 TLS currently unavailable

If clients mandate TLS, mail will be broken.

**Comment by andrewladlow** [comment]
I think this is because `dpkg-reconfigure symbiosis-common` in `/etc/first-boot.d/00-symbiosis-reconfiguration:21` fails, with error:
`Failed to stop symbiosis-skel.path: Unit symbiosis-skel.path not loaded.`

**Comment by andrewladlow** [comment]
Fixed with https://github.com/BytemarkHosting/symbiosis/commit/d9b725d06026a928f0b3324eca98305dc37fa3a9
