### ISSUE TITLE
Stretch - Cron warning emails generated by backup2l 

### ISSUE THREAD

**Issue by andrewladlow** [BytemarkHosting/symbiosis#127]
When the cron script `/etc/cron.daily/zz-backup2l` runs, it generates the following warning message:

> WARNING:
> 
>  Volume is or was locked by another instance of 'backup2l'.
> 
> It appears that another instance of 'backup2l' is or was running concurrently.
> This should not happen, but cannot be avoided completely with the present
> implementation of locking in 'backup2l'. I am sorry!
> 
> The following steps should bring everything back into order:
> 1. Stop all instances of 'backup2l'.
> 2. Remove the lock file '/var/backups/localhost/all.lock' manually.
> 3. Re-run the backup.
> 4. Unmount the backup device (if desired).`

A new backup is created despite this warning message, but it could be a cause for concern.

**Comment by pcammish** [comment]
Fixed in upcoming merge

**Comment by andrewladlow** [comment]
Fixed with https://github.com/BytemarkHosting/symbiosis/commit/bc3fab45e49f5b30fcf99ae9fe4bc8b9c7d65eed
