### ISSUE TITLE
Dovecot security update breaks symbiosis's dovecot integration

### ISSUE THREAD

**Issue by lupine** [BytemarkHosting/symbiosis#13]
Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860049
Dovecot commit: https://github.com/dovecot/core/commit/000030feb7a30f193197f1aab8a7b04a26b42735

Reported by a friend who I convinced to use symbiosis-jessie a while ago. He reports that, after upgrading his machine to the latest version of dovecot from debian security, his authentication to dovecot stopped working. SMTP is still accepting emails, etc.

He reports the following in his logs:

```
symbiosis-email-dict-proxy: Caught too few arguments
dovecot: auth-worker(11354): Error: dict(user@domain,ip): Failed to lookup key shared/passdb/%u
```

**Comment by lupine** [comment]
The first line in the logs must be from here: https://github.com/BytemarkHosting/symbiosis/blob/jessie/email/lib/symbiosis/email/dict_handler.rb#L50

**Comment by lupine** [comment]
Hacking up the logging a bit, I get the following:

```
Apr 11 00:42:08 foo.default.urgs.uk0.bigv.io symbiosis-email-dict-proxy[3826]: "Lshared/passdb/%u": Caught #<ArgumentError: too few arguments>
Apr 11 00:42:08 foo.default.urgs.uk0.bigv.io symbiosis-email-dict-proxy[3826]: /usr/lib/ruby/vendor_ruby/symbiosis/email/dict_handler.rb:73:in `info'
Apr 11 00:42:08 foo.default.urgs.uk0.bigv.io symbiosis-email-dict-proxy[3826]: /usr/lib/ruby/vendor_ruby/symbiosis/email/dict_handler.rb:73:in `do_lookup'
Apr 11 00:42:08 foo.default.urgs.uk0.bigv.io symbiosis-email-dict-proxy[3826]: /usr/lib/ruby/vendor_ruby/symbiosis/email/dict_handler.rb:30:in `receive_line'
Apr 11 00:42:08 foo.default.urgs.uk0.bigv.io symbiosis-email-dict-proxy[3826]: /usr/lib/ruby/vendor_ruby/em/protocols/line_protocol.rb:19:in `receive_data'
Apr 11 00:42:08 foo.default.urgs.uk0.bigv.io symbiosis-email-dict-proxy[3826]: /usr/lib/ruby/vendor_ruby/eventmachine.rb:187:in `run_machine'
Apr 11 00:42:08 foo.default.urgs.uk0.bigv.io symbiosis-email-dict-proxy[3826]: /usr/lib/ruby/vendor_ruby/eventmachine.rb:187:in `run'
Apr 11 00:42:08 foo.default.urgs.uk0.bigv.io symbiosis-email-dict-proxy[3826]: /usr/sbin/symbiosis-email-dict-proxy:104:in `<main>'
```

All the calls to `syslog.*` seem to be broken, they reliably return `ArgumentError` - but the interesting part is that the data line from dovecot now looks like: `Lshared/passdb/%u`

I'm guessing it should be:

`Lshared/passdb/foo.default.urgs.uk0.bigv.io`

dovecot-core version:

```
admin@foo:~/foo.default.urgs.uk0.bigv.io/mailboxes/root$ apt-cache policy dovecot-core
dovecot-core:
  Installed: 1:2.2.13-12~deb8u2
  Candidate: 1:2.2.13-12~deb8u2
  Version table:
     1:2.2.27-2~bpo8+1 0
        100 http://mirror.bytemark.co.uk/debian/ jessie-backports/main amd64 Packages
 *** 1:2.2.13-12~deb8u2 0
        500 http://security.debian.org/ jessie/updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1:2.2.13-12~deb8u1 0
        500 http://mirror.bytemark.co.uk/debian/ jessie/main amd64 Packages
```

this is the one released in response to the mentioned bug. I'm going to try installing`1:2.2.13-12~deb8u1`for a full replication.

**Comment by lupine** [comment]
Yep, with `1:2.2.13-12~deb8u1` installed, the line received by `symbiosis-email-dict-proxy` looks like: `Lshared/passdb/root@foo.default.urgs.uk0.bigv.io`

**Comment by lupine** [comment]
I wonder if this is a backport failure by Debian. I've sent them an email: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860049;msg=17

**Comment by danielhjames** [comment]
Hi, I'm also experiencing this issue on Symbiosis jessie today. My workaround was to downgrade to the previous version of all dovecot packages, which restored functionality:
```
sudo apt-get install dovecot-core=1:2.2.13-12~deb8u1 dovecot-imapd=1:2.2.13-12~deb8u1 
dovecot-managesieved=1:2.2.13-12~deb8u1 dovecot-pop3d=1:2.2.13-12~deb8u1 
dovecot-sieve=1:2.2.13-12~deb8u1
```
Thanks @lupine for helping me to identify the issue, you've saved me much head scratching!

**Comment by matthewbloch** [comment]
Not strictly relevant to the software, but we wrote https://status.bytemark.org/issues/165 
 to acknowlege the issue for our customers and https://forum.bytemark.co.uk/t/fixing-the-symbiosis-imap-login-issue/2602/2 as our official fix-it thread.

Thank you also @lupine 💯

**Comment by skx** [comment]
Debian have now released an update which reverses the regression.

I've updated our forum-post explicitly, but if you've downgraded in the past you should now be able to upgrade to resolve the problem forever:

     sudo apt-get update
     sudo apt-get upgrade

That should give you `dovecot-*` packages with a version number of `1:2.2.13-12~deb8u3`.

**Comment by joolsr** [comment]
I did have to run the apt-get update and upgrade twice with a apt-get -f install in between as I had dependency issues too. I also have roundcube and dovecot-managesieve installed which seems to be underlying these additional niggles.

All running fine eventually now and all dovecot packages at 1:2.2.13-12~deb8u3

**Comment by danielhjames** [comment]
Thanks @skx and @matthewbloch, Bytemark rules :-)

**Comment by skx** [comment]
I think we helped most users out via the forum, and after that Debian released a [security update](https://lists.debian.org/debian-security-announce/2017/msg00087.html) which fixed the regression.

So I'll close this now.

Thanks for the report, @lupine and the diagnostics.   That saved a lot of time for a lot of people :)
