### ISSUE TITLE
Logrotate cron error for prosody when it's not running 

### ISSUE THREAD

**Issue by andrewladlow** [BytemarkHosting/symbiosis#131]
The logrotate cron will email the following warning every week if prosody isn't active:

<pre>
/etc/cron.daily/logrotate:
error: error running shared postrotate script for
'/var/log/prosody/prosody.log /var/log/prosody/prosody.err '
run-parts: /etc/cron.daily/logrotate exited with return code 1
</pre>

It looks like this is because the postrotate tries to check for the existence of `/var/run/prosody/prosody.pid` which won't be there when prosody is disabled (by default):

<pre>
[ -e /var/run/prosody/prosody.pid ] && /etc/init.d/prosody reload > /dev/null
</pre>

We should be able to suppress that by changing this line to e.g 

<pre>
/etc/init.d/prosody reload > /dev/null
</pre>

**Comment by ianeiloart** [comment]
This is a bit of a hack. Suppressing output might make real errors. A better fix is to fix this such that the post rotate script checks that the service is enabled before attempting the reload.
