### ISSUE TITLE
LetsEncrypt are deprecating ACMEv1

### ISSUE THREAD

**Issue by ianeiloart** [BytemarkHosting/symbiosis#141]
LetsEncrypt are deprecating ACMEv1, which is used by Symbiosis.

https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

The short story is that from November 2019, I think, new Symbiosis machines won't be able to create LetsEncrypt accounts. Existing Symbiosis machines, that already have LetsEncrypt certs should be fine.

Perhaps the best solution would be built around certbot.

**Comment by hairy-dog** [comment]
There was a neat workaround for this suggested in the bytemark forums Symbiosis section, but the new owners have now deleted the forums. 
Does anyone recall what the workaround is? I think it was copying something from a different domain.

**Comment by patch0** [comment]
OK, so I've done a small amount of work to get this going.  I've tested it on my own machine (running Debian stretch) and it works for me :)  Famous last words..

See https://gist.github.com/patch0/1be74e58fe5957aa27cfefd56bc813e2

**Comment by DavidGoodwin** [comment]
See - 
 it looks like symbiosis now supports acme v2 https://github.com/BytemarkHosting/symbiosis/commit/5ea4cabc3b0b343ac2406a60ebc2878d70ddca16

**Comment by OllieD** [comment]
Stretch has been updated to support ACME V2 and the fix has also been backported to Jessie.
Updated packages are available on the repository.
