### ISSUE TITLE
symbiosis-httpd-configure needs forcing for SSL

### ISSUE THREAD

**Issue by Dansmithyy** [BytemarkHosting/symbiosis#5]
I recently completely reinstalled my website with WordPress from a clean slate on Symbiosis, I then added all the necessary requirements to enable SSL with Let's Encrypt again, once I added the htaccess file and updated WordPress to use HTTPS, I was getting certificate errors as it was using the default self signed certificate, I then ran symbiosis-httpd-configure --force which fixed the issue.

**Comment by patch0** [comment]
OK, this shouldn't be the case.

The --force flag will basically reset all the apache configuration snippets to match the template.  If you'd edited the configuration snippet for the site, maybe before you'd re-configurated it from scratch, then it would not get automatically overwritten.

Symbiosis deals with quite a lot of tinkering of configuration files etc, and I've tried to keep it as conservative as possible to stop it treading on people's toes, at the expense of being completely automagic.

Thinking aloud, maybe a switch to make configuration management more or less conservative would be an idea.

**Comment by patch0** [comment]
To be honest @Dansmithyy I don't think there is much I can do here to improve things based on this report.  I can't explain why `--force` was needed without going through the same steps as you'd done.  I'll close this report, but if you see it again, more output (running `symbiosis-httpd-configure --verbose`) would help.
