### ISSUE TITLE
common: postinst needs to check for a better valid hostname

### ISSUE THREAD

**Issue by patch0** [BytemarkHosting/symbiosis#57]
The HOSTNAME env variable doesn't tend to bell

It should probably check against a regexp for the presence of a dot in the $HOSTNAME env variable:

```regex
/^[_a-z0-9-]+\.([_a-z0-9-]+\.?)+$/
```

would do the trick

> Originally reported on [Bytemark's Gitlab](https://gitlab.bytemark.co.uk/open-source/symbiosis/issues/66) by @patch0 on 2017-04-21T19:29:30.820Z

**Comment by patch0** [comment]
I think this was following testing inside docker containers, where HOSTNAME gets set weirdly, and really shouldn't be used.

**Comment by telyn** [comment]
it's causing similar problems with systemd containers i think

**Comment by telyn** [comment]
Is this bug meant to fix-up invalid $HOSTNAMEs by appending '.localdomain', or just complain early in the install process?
