### ISSUE TITLE
symbiosis-httpd-logger.go applies non-permission mode bits to log files

### ISSUE THREAD

**Issue by banburybill** [BytemarkHosting/symbiosis#9]
If logging to a directory that has the setgid bit turned on, the logger applies the directory mode to all new files, modulo turning off any execute permission. This means that log files get created with the setgid bit set, though of course not being executable this has no effect.

Except it does have an effect.

gzip: /srv/<mywebsite>/public/logs/ssl_error.log.2 is set-group-ID on execution - ignored
Failed to compress /srv/testconference.accu.org/public/logs/ssl_error.log.2

**Comment by patch0** [comment]
Agreed, and your code looks good.
